Repository woowa-techcamp-2021/store-8, pull requests merged in 2021-08, with the labels that each got.

#4 [#3] project setting 완료
  .gitignore
  .prettierrc.json
  client/custom.d.ts
  client/package-lock.json
  client/package.json
  client/public/image/icon.svg
  client/public/index.html
  client/src/App.tsx
  client/src/GlobalStyle.ts
  client/src/api/.keep
  client/src/components/.keep
  client/src/constants/.keep
  client/src/index.tsx
  client/src/pages/.keep
  client/src/store/.keep
  client/src/utils/.keep
  client/tsconfig.json
  client/webpack.config.js
  client/webpack.dev.js
  client/webpack.prod.js
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/config/config_sample.json
  server/src/constants/common.js
  server/src/constants/error.js
  server/src/constants/success.js
  server/src/errors/custom-error.js
  server/src/middlewares/decode-jwt.js
  server/src/middlewares/error-handler.js
  server/src/middlewares/log.js
  server/src/models/index.js
  server/src/models/user.js
  server/src/routes/index.js
  server/src/routes/user-router.js
  server/src/services/user-service.js
  server/src/utils/bcrypt.js
  server/src/utils/jwt.js
  server/src/utils/make-query.js
  server/src/utils/result-checker.js
  server/src/utils/util-func.js
Labels: setting

#6 [#5] readme 수정
  readme.md
Labels: documentation

#2 [#1] Github 관련 Template 설정했습니다.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#22 [#20] 마이페이지-주문목록/배송조회 페이지 마크업
  client/src/App.tsx
  client/src/GlobalStyle.ts
  client/src/ResetStyle.tsx
  client/src/components/.keep
  client/src/components/MyPage/Intro/Intro.tsx
  client/src/components/MyPage/Intro/style.tsx
  client/src/components/MyPage/NavigationBar/NavigationBar.tsx
  client/src/components/MyPage/OrderSection/OrderSection.tsx
  client/src/components/MyPage/OrderSection/style.ts
  client/src/components/MyPage/SearchBar/SearchBar.tsx
  client/src/components/MyPage/SearchBar/style.tsx
  client/src/index.tsx
  client/src/pages/.keep
  client/src/pages/Mypage/Mypage.tsx
  client/src/pages/Mypage/style.ts
Labels: feature, In Progress

#24 Issue11/shop cart main
  client/custom.d.ts
  client/public/image/cartNextBlack.png
  client/public/image/cartNextGrey.png
  client/public/image/equalCircle.png
  client/public/image/exclamMark.png
  client/public/image/image0.jpg
  client/public/image/image1.jpg
  client/public/image/image2.jpg
  client/public/image/image3.png
  client/public/image/image4.jpg
  client/public/image/plusCircle.png
  client/public/index.html
  client/src/App.tsx
  client/src/GlobalStyle.ts
  client/src/components/Cart/Container/CartContentsContainer.tsx
  client/src/components/Cart/Container/Content/CartContent.tsx
  client/src/components/Cart/Container/Content/style.tsx
  client/src/components/Cart/Container/style.tsx
  client/src/components/Cart/Header/CartHeader.tsx
  client/src/components/Cart/Header/style.tsx
  client/src/components/Cart/Proceed/Proceed.tsx
  client/src/components/Cart/Proceed/style.tsx
  client/src/components/Cart/Receipt/Receipt.tsx
  client/src/components/Cart/Receipt/style.tsx
  client/src/components/common/Button/Button.tsx
  client/src/components/common/Button/style.tsx
  client/src/constants/.keep
  client/src/constants/Cart.ts
  client/src/constants/Media.ts
  client/src/pages/Cart/Cart.tsx
  client/src/pages/Cart/style.tsx
  client/src/pages/Cart/tempData.ts
  client/src/type/CartContentData.ts
  client/src/type/CartContentMetaData.ts
  client/src/utils/.keep
  client/src/utils/utils.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: feature

#33 [FE] 상품 이미지 확대, 세션 탭 전환
  client/App.tsx
  client/GlobalStyle.ts
  client/components/ProductDetail/ImgMagnifier/ImgMagifier.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/ProductDetail/ProductDetail.tsx
  client/components/ProductDetail/ZoomImg/ZoomImg.tsx
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/SectionNav/SectionNav.tsx
  package-lock.json
Labels: feature

#38 [#20] 라우터 변경으로 인한 버그 픽스
  client/App.tsx
  client/pages/OrderPage/OrderPage.tsx
  client/pages/OrderPage/style.ts
  client/pages/RefundPage/RefundPage.tsx
  client/pages/RefundPage/style.ts
  middle/router/routes.ts
Labels: bug

#42 [#41] deploy script
  .github/workflow/*.yml
Labels: feature

#44 Issue26/styled component
  client/components/Auth/style.tsx
  client/components/Button/style.tsx
  client/components/Cart/Container/CartContentsContainer.tsx
  client/components/Cart/Container/Content/style.tsx
  client/components/Cart/Container/style.tsx
  client/components/Cart/Header/style.tsx
  client/components/Cart/Proceed/style.tsx
  client/components/Cart/Receipt/style.tsx
  client/components/Footer/style.tsx
  client/components/ProductDetail/DetailBtns /DetailBtns.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/common/input/Input.tsx
  client/lib/styledComponent.tsx
  tsconfig.json
  webpack.config.js
Labels: feature

#48 상품디테일 - 상품문의 마크업
  client/components/ProductDetail/DetailBtns /DetailBtns.tsx
  client/components/ProductDetail/ProductInfo/style.ts
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/ProductQuestionList/ProductQuestionList.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/QuestionForm.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/QuestionDetail.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionItem.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/style.tsx
  client/components/ProductDetailSection/SectionNav/SectionNav.tsx
  client/components/ProductDetailSection/SectionNav/style.tsx
  client/components/common/CheckBox/CheckBox.tsx
  client/components/common/Modal/Modal.tsx
  client/components/common/Modal/style.tsx
  client/constants/productDetail/productDetailSection/ProductDetailSection.ts
  client/type/question/question.ts
  public/image/question/checkIcon.svg
  public/image/question/lockerIcon.svg
  public/image/question/xIcon.svg
  public/index.html
Labels: feature, style

#60 backend 모델 구현
  .gitignore
  server/controllers/product-question.ts
  server/models/Address.ts
  server/models/Coupon.ts
  server/models/Option.ts
  server/models/Order.ts
  server/models/Product.ts
  server/models/Question.ts
  server/models/Refund.ts
  server/models/Review.ts
  server/models/ReviewImg.ts
  server/models/User.ts
  server/models/UserCoupon.ts
  server/models/Wish.ts
  server/models/index.ts
  server/router/index.ts
  server/router/product-question.ts
Labels: feature

#55 마이페이지 - 주문목록/배송조회 구현
  client/components/MyPage/NavigationBar/NavigationBar.tsx
  client/components/MyPage/OrderSection/OrderSection.tsx
  client/components/MyPage/ResultBox/ResultBox.tsx
  client/components/MyPage/ResultBox/style.ts
  client/components/MyPage/ResultContainer/ResultContainer.tsx
  client/components/MyPage/ResultContainer/style.ts
  client/components/MyPage/SearchBar/SearchBar.tsx
  client/utils/date.ts
Labels: feature

#56 Issue32 / cart backend 구현
  client/api/cart.ts
  client/api/utils/request.ts
  client/components/Cart/Container/CartContentsContainer.tsx
  client/components/Cart/Container/Content/CartContent.tsx
  client/components/Cart/Proceed/Proceed.tsx
  client/components/Header/Header.tsx
  client/components/Header/HeaderCheck.tsx
  client/components/Header/HeaderItem.tsx
  client/components/Header/style.tsx
  client/constants/server_url.ts
  client/index.tsx
  client/pages/Cart/Cart.tsx
  client/pages/Cart/tempData.ts
  client/pages/RegisterPage/RegisterPage.tsx
  client/store/auth/login.ts
  client/store/auth/register.ts
  client/store/createExtra/createExtraPost.ts
  client/store/index.ts
  client/store/product/cart.ts
  client/type/CartContentData.ts
  client/utils/responseTypeChanger.ts
  middle/type/auth/register.ts
  middle/type/cart/cart.ts
  package-lock.json
  server/constants/migration/CARTS.ts
  server/controllers/cart.ts
  server/index.ts
  server/models/Cart.ts
  server/models/Option.ts
  server/models/Product.ts
  server/models/User.ts
  server/models/index.ts
  server/router/cart.ts
  server/router/index.ts
  server/utils/migrate.ts
  tsconfig.json
Labels: feature

#57 [#53] fix: img tag가 2번씩 쓰여지던 문제.
  client/lib/styledComponent.tsx
Labels: bug

#64 [BE] 상품 문의 API
  middle/type/question/question.ts
  server/constants/error.ts
  server/controllers/product-question.ts
  server/controllers/question.ts
  server/models/Question.ts
  server/router/index.ts
  server/router/product-question.ts
  server/router/question.ts
  server/utils/date.ts
  server/utils/jwt.ts
Labels: feature

#66 Issue59 / cart redesign
  client/GlobalStyle.ts
  client/components/Cart/Container/CartContentsContainer.tsx
  client/components/Cart/Container/Content/CartContent.tsx
  client/components/Cart/Container/Content/style.tsx
  client/components/Cart/Container/style.tsx
  client/components/Cart/DeleteModal/DeleteModal.tsx
  client/components/Cart/DeleteModal/style.tsx
  client/components/Cart/Proceed/Proceed.tsx
  client/components/Cart/Proceed/style.tsx
  client/components/Cart/Receipt/Receipt.tsx
  client/components/Cart/Receipt/style.tsx
  client/components/common/Modal/Modal.tsx
  client/components/common/Modal/style.tsx
  client/constants/Cart.ts
  client/pages/Cart/Cart.tsx
  client/pages/Cart/style.tsx
  client/type/CartContentMetaData.ts
  client/utils/responseTypeChanger.ts
  dbInitializer.ts
  middle/type/cart/cart.ts
  package.json
  public/image/checked.png
  public/image/equalCircle.png
  public/image/numDown.png
  public/image/numUp.png
  public/image/plusCircle.png
  public/image/unchecked.png
  server/constants/migration/CARTS.ts
  server/controllers/cart.ts
  server/models/Cart.ts
  server/models/index.ts
  server/utils/migrate.ts
Labels: feature

#68 [#67]카테고리 정렬 구현, 버그 픽스
  client/GlobalStyle.ts
  client/components/Auth/style.tsx
  client/components/Category/Category/Category.tsx
  client/components/Category/Category/style.ts
  client/components/Category/CategoryPagination/PaginationItem.tsx
  client/components/Header/SliderItem.tsx
  client/components/Main/Carousel/style.tsx
  client/constants/category_order.ts
  client/pages/CategoryPage/style.tsx
  client/pages/LoginPage/style.tsx
  client/pages/MainPage/style.tsx
  client/pages/RegisterPage/style.tsx
  public/image/product/.gitkeep
  server/controllers/category.ts
Labels: feature, style

#76 Issue69/main redesign
  client/GlobalStyle.ts
  client/components/Category/Category/style.ts
  client/components/Category/CategoryPagination/style.ts
  client/components/Footer/Footer.tsx
  client/components/Footer/style.tsx
  client/components/Header/DarkMode.tsx
  client/components/Header/Header.tsx
  client/components/Header/style.tsx
  client/components/Main/Carousel/style.tsx
  client/components/Main/MainGift/style.tsx
  client/components/Main/common/style.ts
  client/pages/MainPage/style.tsx
  client/utils/setDisplay.ts
  public/image/appIconLine.png
  public/image/appIconStack.png
Labels: feature, style

#80 상품 문의 조회 api 연동
  client/api/question.ts
  client/api/utils/request.ts
  client/components/ProductDetailSection/ProductQuestionList/ProductQuestionList.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/QuestionDetail.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionItem.tsx
  client/hooks/question/question.ts
  client/store/index.ts
  client/store/product/question.ts
  server/constants/migration/QUESTION.ts
  server/controllers/question.ts
Labels: feature

#81 Revert "Issue69/main redesign"
  client/GlobalStyle.ts
  client/components/Category/Category/style.ts
  client/components/Category/CategoryPagination/style.ts
  client/components/Footer/Footer.tsx
  client/components/Footer/style.tsx
  client/components/Header/DarkMode.tsx
  client/components/Header/Header.tsx
  client/components/Header/style.tsx
  client/components/Main/Carousel/style.tsx
  client/components/Main/MainGift/style.tsx
  client/components/Main/common/style.ts
  client/pages/MainPage/style.tsx
  client/utils/setDisplay.ts
  public/image/appIconLine.png
  public/image/appIconStack.png
Labels: bug

#82 API 연동 및 마크업 작업 ( 데모 )
  client/components/Header/Header/HeaderCheck.tsx
  client/components/MyPage/NavigationBar/NavigationBar.tsx
  client/components/MyPage/OrderBox/OrderBox.tsx
  client/components/MyPage/OrderBox/style.ts
  client/components/MyPage/OrderResultContainer/OrderResultContainer.tsx
  client/components/MyPage/OrderResultContainer/style.ts
  client/components/MyPage/OrderSection/OrderSection.tsx
  client/components/MyPage/RefundBox/RefundBox.tsx
  client/components/MyPage/RefundBox/style.ts
  client/components/MyPage/RefundFilter/RefundFilter.tsx
  client/components/MyPage/RefundFilter/style.ts
  client/components/MyPage/RefundResultContainer/RefundResultContainer.tsx
  client/components/MyPage/RefundResultContainer/style.ts
  client/components/MyPage/RefundSection/RefundSection.tsx
  client/components/MyPage/SearchBar/SearchBar.tsx
  client/components/MyPage/dummydata.ts
  client/pages/MyRefundPage/style.ts
  middle/router/routes.ts
  server/constants/migration/ORDERS.ts
  server/constants/migration/REFUNDS.ts
  server/controllers/order.ts
  server/controllers/refund.ts
  server/models/Order.ts
  server/models/Refund.ts
  server/models/User.ts
  server/router/index.ts
  server/router/order.ts
  server/router/refund.ts
  server/utils/make-query.ts
Labels: feature

#87 상품문의 API 연동
  client/api/question.ts
  client/components/ProductDetailSection/ProductQuestionList/ProductQuestionList.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/QuestionForm.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/QuestionDetail.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionItem.tsx
  client/components/common/DeleteModal/DeleteModal.tsx
  client/hooks/question/question.ts
  client/store/product/question.ts
  client/utils/fetchWrapper.ts
  custom.d.ts
  middle/type/question/question.ts
  public/image/icon/clipIcon.svg
  public/image/icon/deleteIcon.svg
  public/image/icon/editIcon.svg
Labels: feature

#90 [FE] 상품문의 CRUD API 연동
  client/api/review.ts
  client/api/upload.ts
  client/components/ProductDetail/ImgMagnifier/ImgMagifier.tsx
  client/components/ProductDetail/ProductDetail.tsx
  client/components/ProductDetailSection/DetailInfo/DetailInfo.tsx
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/ProductQuestionList/ProductQuestionList.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/QuestionForm.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/QuestionDetail.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionItem.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ProductReviewList.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ImgListForm/ImgItem.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ImgListForm/ImgListForm.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ReviewForm.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ScoreChecker/ScoreChecker.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewDetail/ReviewDetail.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewDetail/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewItem.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/style.tsx
  client/components/ProductDetailSection/style.tsx
  client/components/common/Star/Star.tsx
  client/hooks/product/product.ts
  client/hooks/question/question.ts
  client/hooks/review/review.ts
  client/store/index.ts
  client/store/product/review.ts
  client/utils/encode.ts
  middle/type/question/question.ts
  middle/type/review/review.ts
  public/image/icon/dislikeIcon.svg
  public/image/icon/likeIcon.svg
  public/image/icon/plusIcon.svg
  public/image/icon/starIcon.svg
  public/image/icon/xIcon.svg
  public/image/question/xIcon.svg
  server/controllers/question.ts
  server/controllers/review.ts
  server/controllers/upload.ts
  server/middleware/uploadImage.ts
  server/router/upload.ts
  webpack.dev.js
Labels: feature

#92 [BE] #12 주문하기 BE 작업 + modal
  client/api/address.ts
  client/api/coupon.ts
  client/api/order.ts
  client/components/Cart/Container/CartContentsContainer.tsx
  client/components/Cart/Container/style.tsx
  client/components/Order/AccountInfo/style.tsx
  client/components/Order/AddressModal/Address.tsx
  client/components/Order/AddressModal/AddressModal.tsx
  client/components/Order/AddressModal/style.tsx
  client/components/Order/CouponModal/CouponModal.tsx
  client/components/Order/OrderDetail/style.tsx
  client/components/Order/OrderReceipt/OrderReceipt.tsx
  client/components/Order/UserInfo/UserInfo.tsx
  client/components/Order/UserInfo/style.tsx
  client/components/common/AlertInput/AlertInput.tsx
  client/components/common/AlertInput/style.tsx
  client/constants/Order.ts
  client/hooks/order/order.ts
  client/lib/daumAddress.ts
  client/pages/CartPage/CartPage.tsx
  client/pages/OrderPage/OrderPage.tsx
  client/store/address/address.ts
  client/store/coupon/coupon.ts
  client/store/index.ts
  client/utils/responseTypeChanger.ts
  middle/router/routes.ts
  middle/type/Coupon/coupon.ts
  middle/type/address/address.ts
  middle/type/cart/cart.ts
  middle/type/product/order.ts
  public/index.html
  server/constants/migration/ADDRESSES.ts
  server/constants/migration/COUPONS.ts
  server/constants/migration/ORDERS.ts
  server/controllers/address.ts
  server/controllers/cart.ts
  server/controllers/coupon.ts
  server/controllers/order.ts
  server/models/Address.ts
  server/models/Coupon.ts
  server/models/Order.ts
  server/models/User.ts
  server/models/UserCoupon.ts
  server/router/address.ts
  server/router/coupon.ts
  server/router/index.ts
  server/router/order.ts
  server/utils/createPage.ts
  server/utils/migrate.ts
  server/utils/orderNumber.ts
Labels: feature

#96 Issue69/footer
  client/components/Footer/Footer.tsx
  client/components/Footer/style.tsx
  client/components/Header/Dark/DarkMode.tsx
  client/components/Header/Header/Header.tsx
  client/components/Header/style.tsx
  client/lib/styledComponent.tsx
  client/utils/setDisplay.ts
  public/favicon.ico
  public/image/image0.jpg
  public/image/image1.jpg
  public/image/image2.jpg
  public/image/image3.png
  public/image/image4.jpg
  public/image/svg/mainHorizontal.svg
  public/image/svg/mainVertical.svg
  public/image/svg/moon.svg
  public/image/svg/sun.svg
Labels: feature, style

#98 [BE] server url to dot env
  client/constants/server_url.ts
Labels: feature

#101 [FE] 옵션 선택 기능
  client/components/ProductDetail/DetailBtns /style.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/ProductDetail/ProductDetail.tsx
  client/components/ProductDetail/ProductInfo/ProductCountForm/ProductCountForm.tsx
  client/components/ProductDetail/ProductInfo/ProductCountForm/style.tsx
  client/components/ProductDetail/ProductInfo/ProductInfo.tsx
  client/components/ProductDetail/ProductInfo/ProductInfoCount.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/ProductOption.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/ProductOptionItem.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/style.tsx
  client/components/ProductDetail/ProductInfo/style.ts
  client/components/ProductDetail/style.ts
  client/hooks/product/product.ts
  client/store/product/product.ts
  client/utils/setDisplay.ts
  middle/type/product/options.ts
  public/image/icon/arrowDownIcon.svg
Labels: feature, style

#108 [FE] 메인 - 메인 장바구니 관련
  client/api/product.ts
  client/components/Card/Card.tsx
  client/components/Card/Cart/Cart.tsx
  client/components/Card/Cart/style.tsx
  client/components/Card/OptionModal/Option.tsx
  client/components/Card/OptionModal/OptionModal.tsx
  client/components/Card/OptionModal/style.tsx
  client/components/Card/style.tsx
  client/components/Header/Header/HeaderCheck.tsx
  client/components/Header/style.tsx
  client/components/Main/MainGift/MainGift.tsx
  client/components/Main/MainGift/style.tsx
  client/components/Main/common/style.ts
  client/components/Wish/Wish.tsx
  client/constants/Order.ts
  client/hooks/product/cart.ts
  client/hooks/product/option.ts
  client/pages/MainPage/style.tsx
  client/store/product/cart.ts
  middle/type/cart/cart.ts
  public/image/svg/cart.svg
  server/controllers/product.ts
  server/router/product.ts
  server/utils/createPage.ts
Labels: feature, style

#103 [FE] Issue18 주문 완료 화면
  client/api/address.ts
  client/api/order.ts
  client/components/Cart/Receipt/Receipt.tsx
  client/components/Order/OrderFinishContents/OrderFinishContents.tsx
  client/components/Order/OrderFinishContents/OrderPlace/OrderPlace.tsx
  client/components/Order/OrderFinishContents/OrderPlace/style.tsx
  client/components/Order/OrderFinishContents/style.tsx
  client/components/Order/OrderReceipt/OrderReceipt.tsx
  client/components/Order/UserInfo/UserInfo.tsx
  client/components/Order/UserInfo/style.tsx
  client/components/common/AlertInput/AlertInput.tsx
  client/hooks/order/order.ts
  client/lib/daumAddress.ts
  client/pages/OrderFinishPage/OrderFinishPage.tsx
  client/pages/OrderFinishPage/style.tsx
  client/pages/OrderPage/OrderPage.tsx
  client/store/index.ts
  client/store/product/finish.ts
  client/store/product/order.ts
  client/type/CartContentMetaData.ts
  client/utils/createToast.ts
  client/utils/inputTypeChecker.ts
  client/utils/router.tsx
  middle/router/routes.ts
  middle/type/address/address.ts
  middle/type/product/order.ts
  server/constants/migration/USERS.ts
  server/controllers/address.ts
  server/controllers/auth.ts
  server/controllers/github.ts
  server/controllers/order.ts
  server/models/Product.ts
  server/models/User.ts
  server/router/address.ts
  server/router/order.ts
  server/utils/migrate.ts
Labels: feature

#112 [FE] 상세페이지 디테일 작업들
  client/components/ProductDetail/DetailBtns /DetailBtns.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/QuestionForm.tsx
  client/components/ProductDetailSection/ProductQuestionList/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ReviewForm.tsx
  client/components/ProductDetailSection/ProductReviewList/style.tsx
  client/components/ProductDetailSection/SectionNav/SectionNav.tsx
  client/components/ProductDetailSection/SectionNav/style.tsx
  client/components/common/Modal/Modal.tsx
  client/pages/ProductDetailPage/style.tsx
  client/type/question/question.ts
  client/utils/performance.ts
  client/utils/utils.ts
Labels: feature

#118 [FE] My Page Address Page
  client/api/address.ts
  client/api/coupon.ts
  client/components/MyPage/AddressSection/AddressAddModal/AddressAddModal.tsx
  client/components/MyPage/AddressSection/AddressAddModal/style.tsx
  client/components/MyPage/AddressSection/AddressDeleteModal/AddressDeleteModal.tsx
  client/components/MyPage/AddressSection/AddressDeleteModal/style.tsx
  client/components/MyPage/AddressSection/AddressModifyModal/AddressModifyModal.tsx
  client/components/MyPage/AddressSection/AddressModifyModal/style.tsx
  client/components/MyPage/AddressSection/AddressResult/AddressResult.tsx
  client/components/MyPage/AddressSection/AddressResult/style.ts
  client/components/MyPage/AddressSection/AddressSection.tsx
  client/components/MyPage/AddressSection/style.tsx
  client/components/MyPage/Intro/CouponModal/CouponModal.tsx
  client/components/MyPage/Intro/CouponModal/style.tsx
  client/components/MyPage/Intro/Intro.tsx
  client/components/common/AlertInput/AlertInput.tsx
  client/components/common/AlertInput/style.tsx
  client/constants/Cart.ts
  client/hooks/order/coupon.ts
  client/hooks/order/order.ts
  client/pages/MyAddressPage/MyAddressPage.tsx
  client/pages/OrderPage/OrderPage.tsx
  client/store/product/finish.ts
  client/utils/setDisplay.ts
  middle/type/address/address.ts
  server/controllers/address.ts
  server/controllers/coupon.ts
  server/router/address.ts
  server/router/coupon.ts
Labels: feature

#121 [FE] Issue119 / footer detail
  client/components/Footer/Footer.tsx
  client/components/Footer/style.tsx
  client/pages/PrivatePage/PrivatePage.tsx
  client/pages/PrivatePage/style.tsx
  client/pages/UsagePage/UsagePage.tsx
  client/pages/UsagePage/style.tsx
  middle/router/routes.ts
Labels: feature, style

#117 이전 PR에서 지우지 못하거나, 처리하지 못한 오류 해결, 마이페이지 레이아웃 통일
  client/api/myOrder.ts
  client/api/myRefund.ts
  client/components/MyPage/MyWishResultContainer/MyWishResultContainer.tsx
  client/components/MyPage/MyWishResultContainer/style.ts
  client/components/MyPage/OrderBox/style.ts
  client/components/MyPage/OrderResultContainer/OrderResultContainer.tsx
  client/components/MyPage/OrderResultContainer/style.ts
  client/components/MyPage/OrderSection/style.ts
  client/components/MyPage/ProductBox/style.ts
  client/components/MyPage/RefundFilter/RefundFilter.tsx
  client/components/MyPage/RefundResultContainer/RefundResultContainer.tsx
  client/components/MyPage/RefundSection/RefundSection.tsx
  client/components/MyPage/common/style.tsx
  client/pages/MyOrderPage/style.ts
  client/pages/MyRefundPage/style.ts
  client/pages/MyWishPage/MyWishPage.tsx
  client/pages/MyWishPage/style.ts
  server/controllers/refund.ts
Labels: refactoring

#169 상품 디테일 페이지 모바일 반응형
  client/components/ProductDetail/ImgMagnifier/ImgMagifier.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/ProductDetail/ProductDetail.tsx
  client/components/ProductDetail/ProductInfo/ProductInfo.tsx
  client/components/ProductDetail/ProductInfo/ProductInfoTitle.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/style.tsx
  client/components/ProductDetail/ProductInfo/style.ts
  client/components/ProductDetail/style.ts
  client/components/ProductDetailSection/DetailInfo/style.tsx
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/QuestionDetail.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ImgListForm/ImgListForm.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewDetail/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/style.tsx
  client/components/ProductDetailSection/SectionNav/style.tsx
  client/components/ProductDetailSection/style.tsx
  client/components/common/ResponseComp/ResponseComp.tsx
  client/hooks/useResponse.tsx
  client/pages/ProductDetailPage/ProductDetailPage.tsx
  client/pages/ProductDetailPage/style.tsx
Labels: feature, style

#174 [FE] Issue170 - 금요일에 있던 QA 바탕으로 작업 진행
  client/api/cart.ts
  client/components/Auth/Auth.tsx
  client/components/Cart/Container/CartContentsContainer.tsx
  client/components/Cart/Container/Content/CartContent.tsx
  client/components/Cart/Container/Content/style.tsx
  client/components/Cart/DeleteModal/DeleteModal.tsx
  client/components/Cart/DeleteModal/style.tsx
  client/components/Cart/Receipt/Receipt.tsx
  client/components/Cart/Receipt/style.tsx
  client/components/Header/Dark/DarkMode.tsx
  client/components/Header/GoIntro/GoIntro.tsx
  client/components/Header/GoIntro/style.tsx
  client/components/Header/Header/Header.tsx
  client/components/Header/Recommend/Recommend.tsx
  client/components/Header/Recommend/style.tsx
  client/components/Header/Search/ElaItem.tsx
  client/components/Header/Search/TagItem.tsx
  client/components/Header/Search/style.tsx
  client/components/Header/Store/StoreMode.tsx
  client/components/Header/Store/style.tsx
  client/components/Header/style.tsx
  client/components/InnerCard/style.tsx
  client/components/MyPage/AddressSection/AddressModifyModal/AddressModifyModal.tsx
  client/components/MyPage/AddressSection/AddressSection.tsx
  client/components/Order/AccountInfo/style.tsx
  client/components/Order/OrderDetail/OrderDetailContents/OrderDetailContents.tsx
  client/components/Order/OrderDetail/OrderDetailContents/style.tsx
  client/components/Order/UserInfo/UserInfo.tsx
  client/components/Order/UserInfo/style.tsx
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/QuestionForm.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/common/Captcha/Captcha.tsx
  client/components/common/Captcha/style.tsx
  client/hooks/order/cart.ts
  client/pages/CartPage/CartPage.tsx
  client/pages/MainPage/style.tsx
  client/pages/OrderPage/OrderPage.tsx
  client/store/product/cart.ts
  client/utils/captcha.ts
  client/utils/responseTypeChanger.ts
  middle/type/cart/cart.ts
  public/image/cartNextBlack.png
  public/image/cartNextGrey.png
  public/image/svg/regen.svg
  public/image/svg/sun.svg
  public/index.html
  server/controllers/cart.ts
  server/router/cart.ts
  server/router/order.ts
  server/utils/createPage.ts
Labels: bug, feature, style

#175 QA시간 버그 수정 및 import 정리
  client/components/ProductDetail/DetailBtns /DetailBtns.tsx
  client/components/ProductDetail/DetailBtns /style.tsx
  client/components/ProductDetail/ImgMagnifier/ImgMagifier.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/ProductDetail/ProductDetail.tsx
  client/components/ProductDetail/ProductInfo/ProductInfo.tsx
  client/components/ProductDetail/ProductInfo/ProductInfoCount.tsx
  client/components/ProductDetail/style.ts
  client/components/ProductDetailSection/ProductDetailSection.tsx
  client/components/ProductDetailSection/ProductQuestionList/ProductQuestionList.tsx
  client/components/ProductDetailSection/ProductReviewList/ProductReviewList.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ImgListForm/ImgListForm.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ReviewForm.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ScoreChecker/ScoreChecker.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewDetail/ReviewDetail.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewItem.tsx
  client/components/ProductDetailSection/SectionNav/SectionNav.tsx
  client/components/Search/Search/Search.tsx
  client/components/Search/SearchPagination/PaginationItem.tsx
  client/components/Search/SearchPagination/SearchPagination.tsx
  client/pages/ProductDetailPage/style.tsx
Labels: bug, feature, style

#179 8월 29일 마지막 QA
  client/components/Auth/Auth.tsx
  client/components/Auth/style.tsx
  client/components/Intro/info/InfoItem.tsx
  client/components/Intro/style.tsx
  client/components/MyPage/EditProfileModal/EditProfileModal.tsx
  client/components/ProductDetail/ImgMagnifier/style.tsx
  client/components/common/AlertModal/style.tsx
  client/components/common/Captcha/style.tsx
  client/pages/OrderFinishPage/OrderFinishPage.tsx
  client/utils/validate.ts
  server/controllers/auth.ts
Labels: bug, feature, style

#182 마이페이지 반응형 - 조회 결과 컨터이너 및 결과박스 작업
  client/components/MyPage/Intro/style.tsx
  client/components/MyPage/MyReviewResultcontainer/style.tsx
  client/components/MyPage/NavigationSmallBar/style.ts
  client/components/MyPage/OrderBox/OrderBox.tsx
  client/components/MyPage/OrderBox/style.ts
  client/components/MyPage/OrderResultContainer/OrderResultContainer.tsx
  client/components/MyPage/OrderResultContainer/style.ts
  client/components/MyPage/RefundBox/RefundBox.tsx
  client/components/MyPage/RefundBox/style.ts
  client/components/MyPage/SearchBar/style.tsx
  client/components/MyPage/common/style.tsx
  client/pages/MyGoodsReviewPage/MyGoodsReviewPage.tsx
  client/pages/MyGoodsReviewPage/style.ts
  server/controllers/refund.ts
Labels: feature

#185 [FE] 마이페이지 상품문의, 상품후기 / 문의,후기 모달 폼 반응형
  client/components/MyPage/MyQuestionBox/MyQuestionBox.tsx
  client/components/MyPage/MyQuestionBox/style.tsx
  client/components/MyPage/MyQuestionResultcontainer/MyQuestionResultContainer.tsx
  client/components/MyPage/MyQuestionResultcontainer/style.tsx
  client/components/MyPage/MyReviewBox/MyReviewBox.tsx
  client/components/MyPage/MyReviewBox/style.tsx
  client/components/MyPage/MyReviewResultcontainer/MyReviewResultContainer.tsx
  client/components/MyPage/MyReviewResultcontainer/style.tsx
  client/components/MyPage/MyReviewSection/style.tsx
  client/components/ProductDetail/ImgMagnifier/ImgMagifier.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/ProductOptionItem.tsx
  client/components/ProductDetail/ProductInfo/ProductOption/style.tsx
  client/components/ProductDetail/style.ts
  client/components/ProductDetailSection/ProductQuestionList/QuestionForm/style.tsx
  client/components/ProductDetailSection/ProductQuestionList/QuestionItem/QuestionDetail/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ScoreChecker/ScoreChecker.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewItem/ReviewDetail/style.tsx
  client/hooks/useResponse.tsx
  client/pages/MyGoodsQAPage/MyGoodsQAPage.tsx
  client/pages/MyGoodsQAPage/style.ts
  client/pages/MyGoodsReviewPage/MyGoodsReviewPage.tsx
Labels: style

#188 [#187] fix: local cart add.
  client/utils/cart.ts
Labels: bug

#189 전체적인 반응형 및 데모영상촬영시 발견한 버그 수정
  client/components/Main/MainBest/MainBest.tsx
  client/components/MyPage/NavigationSmallBar/style.ts
  client/components/MyPage/OrderBox/OrderBox.tsx
  client/components/MyPage/OrderBox/style.ts
  client/components/MyPage/OrderResultContainer/OrderResultContainer.tsx
  client/components/MyPage/OrderResultContainer/style.ts
  client/components/MyPage/RefundBox/RefundBox.tsx
  client/components/MyPage/RefundBox/style.ts
  client/components/MyPage/SearchBar/style.tsx
  client/components/MyPage/common/style.tsx
  client/components/ProductDetailSection/ProductReviewList/ReviewForm/ReviewForm.tsx
  client/hooks/myOrder/myOrder.ts
Labels: bug, style

#191 [#190] fix: 상세페이지 클린업
  client/pages/ProductDetailPage/ProductDetailPage.tsx
Labels: bug

#193 [FIX] 이미지업로드, 상품번호 에러추가
  client/api/upload.ts
  client/hooks/product/product.ts
  scripts/after_deploy.sh
Labels: bug

#198 [#197] fix: 상품 후기 중복 작성 오류 수정
  client/components/ProductDetailSection/ProductReviewList/ProductReviewList.tsx
  client/hooks/order/orderProduct.ts
Labels: bug
